-----------------------------
table_name                   
-----------------------------
alertas_notificaciones       
almacenes                    
almacenes_puntos_venta       
analitica_productos          
arqueos_detalle              
asistencias                  
bancos                       
cajas                        
cargos                       
carritos_compra              
categorias                   
clientes                     
comprobantes_pagos           
concentraciones              
contratos                    
control_facturas             
conversiones_unidad          
costos_promedio              
cufd                         
cuis                         
detalles_carritos            
detalles_pedidos_online      
empresas                     
empresas_cuentas             
empresas_nits                
entrenamientos               
equivalentes                 
especialidades               
formas                       
historicos                   
instituciones                
inventarios_fisicos          
inventarios_fisicos_detalle  
kardex                       
kardex_productos             
laboratorios                 
listas_precios               
logs_ejecucion               
lotes_productos              
marcas                       
medicos                      
menus                        
metricas_rendimiento         
modelos                      
movimientos                  
ordenes_compra               
pagos                        
parametros_globales          
patrones_consumo             
pedidos_online               
planes_pagos                 
planillas                    
planillas_detalle            
politicas_precios            
precios_productos            
presentaciones               
principios_activos           
productos                    
productos_controlados        
productos_principios         
productos_rangos_edad        
productos_ubicaciones        
productos_vias               
promociones                  
promociones_productos        
proveedores                  
proveedores_contactos        
proveedores_rating_historico 
puntos_venta                 
rangos_edad                  
recetas                      
registros_sanitarios         
roles                        
roles_menus                  
roles_permisos_sucesos       
roles_permisos_tablas        
sucesos                      
sucursales                   
tablas                       
tareas_programadas           
tipos_cambios                
tipos_planes_pago            
trabajadores                 
trabajadores_cargos          
ubicaciones                  
ubicaciones_historial        
ubicaciones_movimientos      
umbrales_configuracion       
unidades                     
usuarios                     
variables_exogenas           
vias                         
-----------------------------
Total de filas: 92

aqui puedes crear un archivo C:\sirena\sirena-backend\src\common\constants 
que contenga 
const nombresAmigables: Record<string, string> = {
    empresas_cuentas: 'Cuentas Bancarias',
    clientes: 'Clientes',
    comprobantes_pagos: 'Comprobantes de Pagos',
};
