// C:\sirena\sirena-backend\src\common\constants\nombres-tablas.constant.ts

export interface InfoTablaAmigable {
    singular: string;
    plural: string;
}

export const NOMBRES_TABLAS_AMIGABLES: Record<string, InfoTablaAmigable> = {
    alertas_notificaciones: { singular: 'la alerta y notificación', plural: 'Alertas y Notificaciones' },
    almacenes: { singular: 'el almacén', plural: 'Almacenes' },
    almacenes_puntos_venta: { singular: 'el almacén de punto de venta', plural: 'Almacenes de Puntos de Venta' },
    analitica_productos: { singular: 'la analítica de productos', plural: 'Analítica de Productos' },
    arqueos_detalle: { singular: 'el detalle de arqueos', plural: 'Detalle de Arqueos' },
    asistencias: { singular: 'la asistencia', plural: 'Asistencias' },
    bancos: { singular: 'el banco', plural: 'Bancos' },
    cajas: { singular: 'la caja', plural: 'Cajas' },
    cargos: { singular: 'el cargo', plural: 'Cargos' },
    carritos_compra: { singular: 'el carrito de compra', plural: 'Carritos de Compra' },
    categorias: { singular: 'la categoría', plural: 'Categorías' },
    clientes: { singular: 'el cliente', plural: 'Clientes' },
    comprobantes_pagos: { singular: 'el comprobante de pago', plural: 'Comprobantes de Pagos' },
    concentraciones: { singular: 'la concentración', plural: 'Concentraciones' },
    contratos: { singular: 'el contrato', plural: 'Contratos' },
    control_facturas: { singular: 'el control de facturas', plural: 'Control de Facturas' },
    conversiones_unidad: { singular: 'la conversión de unidad', plural: 'Conversiones de Unidad' },
    costos_promedio: { singular: 'el costo promedio', plural: 'Costos Promedio' },
    cufd: { singular: 'el CUFD', plural: 'CUFD' },
    cuis: { singular: 'el CUIS', plural: 'CUIS' },
    detalles_carritos: { singular: 'el detalle de carrito', plural: 'Detalles de Carritos' },
    detalles_pedidos_online: { singular: 'el detalle de pedido online', plural: 'Detalles de Pedidos Online' },
    empresas: { singular: 'la empresa', plural: 'Empresas' },
    empresas_cuentas: { singular: 'la cuenta bancaria', plural: 'Cuentas Bancarias' },
    empresas_nits: { singular: 'el NIT de empresa', plural: 'NITs de Empresas' },
    entrenamientos: { singular: 'el entrenamiento', plural: 'Entrenamientos' },
    equivalentes: { singular: 'el equivalente', plural: 'Equivalentes' },
    especialidades: { singular: 'la especialidad', plural: 'Especialidades' },
    formas: { singular: 'la forma', plural: 'Formas' },
    historicos: { singular: 'el histórico', plural: 'Históricos' },
    instituciones: { singular: 'la institución', plural: 'Instituciones' },
    inventarios_fisicos: { singular: 'el inventario físico', plural: 'Inventarios Físicos' },
    inventarios_fisicos_detalle: { singular: 'el detalle de inventario físico', plural: 'Detalle de Inventarios Físicos' },
    kardex: { singular: 'el kardex', plural: 'Kardex' },
    kardex_productos: { singular: 'el kardex de productos', plural: 'Kardex de Productos' },
    laboratorios: { singular: 'el laboratorio', plural: 'Laboratorios' },
    listas_precios: { singular: 'la lista de precios', plural: 'Listas de Precios' },
    logs_ejecucion: { singular: 'el log de ejecución', plural: 'Logs de Ejecución' },
    lotes_productos: { singular: 'el lote de productos', plural: 'Lotes de Productos' },
    marcas: { singular: 'la marca', plural: 'Marcas' },
    medicos: { singular: 'el médico', plural: 'Médicos' },
    menus: { singular: 'el menú', plural: 'Menús' },
    metricas_rendimiento: { singular: 'la métrica de rendimiento', plural: 'Métricas de Rendimiento' },
    modelos: { singular: 'el modelo', plural: 'Modelos' },
    movimientos: { singular: 'el movimiento', plural: 'Movimientos' },
    ordenes_compra: { singular: 'la orden de compra', plural: 'Órdenes de Compra' },
    pagos: { singular: 'el pago', plural: 'Pagos' },
    parametros_globales: { singular: 'el parámetro global', plural: 'Parámetros Globales' },
    patrones_consumo: { singular: 'el patrón de consumo', plural: 'Patrones de Consumo' },
    pedidos_online: { singular: 'el pedido online', plural: 'Pedidos Online' },
    planes_pagos: { singular: 'el plan de pagos', plural: 'Planes de Pagos' },
    planillas: { singular: 'la planilla', plural: 'Planillas' },
    planillas_detalle: { singular: 'el detalle de planillas', plural: 'Detalle de Planillas' },
    politicas_precios: { singular: 'la política de precios', plural: 'Políticas de Precios' },
    precios_productos: { singular: 'el precio de productos', plural: 'Precios de Productos' },
    presentaciones: { singular: 'la presentación', plural: 'Presentaciones' },
    principios_activos: { singular: 'el principio activo', plural: 'Principios Activos' },
    productos: { singular: 'el producto', plural: 'Productos' },
    productos_controlados: { singular: 'el producto controlado', plural: 'Productos Controlados' },
    productos_principios: { singular: 'el principio de producto', plural: 'Principios de Productos' },
    productos_rangos_edad: { singular: 'el rango de edad de producto', plural: 'Rangos de Edad de Productos' },
    productos_ubicaciones: { singular: 'la ubicación de producto', plural: 'Ubicaciones de Productos' },
    productos_vias: { singular: 'la vía de producto', plural: 'Vías de Productos' },
    promociones: { singular: 'la promoción', plural: 'Promociones' },
    promociones_productos: { singular: 'la promoción de productos', plural: 'Promociones de Productos' },
    proveedores: { singular: 'el proveedor', plural: 'Proveedores' },
    proveedores_contactos: { singular: 'el contacto de proveedor', plural: 'Contactos de Proveedores' },
    proveedores_rating_historico: { singular: 'el rating histórico de proveedor', plural: 'Rating Histórico de Proveedores' },
    puntos_venta: { singular: 'el punto de venta', plural: 'Puntos de Venta' },
    rangos_edad: { singular: 'el rango de edad', plural: 'Rangos de Edad' },
    recetas: { singular: 'la receta', plural: 'Recetas' },
    registros_sanitarios: { singular: 'el registro sanitario', plural: 'Registros Sanitarios' },
    roles: { singular: 'el rol', plural: 'Roles' },
    roles_menus: { singular: 'el rol de menú', plural: 'Roles de Menús' },
    roles_permisos_sucesos: { singular: 'el permiso de suceso de rol', plural: 'Permisos de Sucesos de Roles' },
    roles_permisos_tablas: { singular: 'el permiso de tabla de rol', plural: 'Permisos de Tablas de Roles' },
    sucesos: { singular: 'el suceso', plural: 'Sucesos' },
    sucursales: { singular: 'la sucursal', plural: 'Sucursales' },
    tablas: { singular: 'la tabla', plural: 'Tablas' },
    tareas_programadas: { singular: 'la tarea programada', plural: 'Tareas Programadas' },
    tipos_cambios: { singular: 'el tipo de cambio', plural: 'Tipos de Cambio' },
    tipos_planes_pago: { singular: 'el tipo de plan de pago', plural: 'Tipos de Planes de Pago' },
    trabajadores: { singular: 'el trabajador', plural: 'Trabajadores' },
    trabajadores_cargos: { singular: 'el cargo de trabajador', plural: 'Cargos de Trabajadores' },
    ubicaciones: { singular: 'la ubicación', plural: 'Ubicaciones' },
    ubicaciones_historial: { singular: 'el historial de ubicación', plural: 'Historial de Ubicaciones' },
    ubicaciones_movimientos: { singular: 'el movimiento de ubicación', plural: 'Movimientos de Ubicaciones' },
    umbrales_configuracion: { singular: 'el umbral de configuración', plural: 'Umbrales de Configuración' },
    unidades: { singular: 'la unidad', plural: 'Unidades' },
    usuarios: { singular: 'el usuario', plural: 'Usuarios' },
    variables_exogenas: { singular: 'la variable exógena', plural: 'Variables Exógenas' },
    vias: { singular: 'la vía', plural: 'Vías' },
};

export function obtenerDatosTablaAmigable(nombreTablaTecnica: string): InfoTablaAmigable {
    return NOMBRES_TABLAS_AMIGABLES[nombreTablaTecnica] || {
        singular: `el registro de ${nombreTablaTecnica}`,
        plural: nombreTablaTecnica,
    };
}

export function obtenerNombreAmigableTabla(nombreTablaTecnica: string): string {
    return NOMBRES_TABLAS_AMIGABLES[nombreTablaTecnica]?.plural || nombreTablaTecnica;
}
