// C:\sirena\sirena-backend\src\common\constants\tablas.constant.ts

export const TABLAS = {
    BANCOS: 'bancos',
    TIPOS_CAMBIOS: 'tipos_cambios',
    EMPRESAS: 'empresas',
    EMPRESAS_NITS: 'empresas_nits',
    EMPRESAS_CUENTAS: 'empresas_cuentas',
    SUCURSALES: 'sucursales',
    PUNTOS_VENTA: 'puntos_venta',
    CUIS: 'cuis',
    CUFD: 'cufd',
    UNIDADES: 'unidades',
    ALMACENES: 'almacenes',
    UBICACIONES: 'ubicaciones',
    ALMACENES_PUNTOS_VENTA: 'almacenes_puntos_venta',
    CARGOS: 'cargos',
    TRABAJADORES: 'trabajadores',
    TRABAJADORES_CARGOS: 'trabajadores_cargos',
    ROLES: 'roles',
    USUARIOS: 'usuarios',
    ROLES_TABLAS: 'roles_tablas',
    MENUS: 'menus',
    ROLES_MENUS: 'roles_menus',
    INVENTARIOS_FISICOS: 'inventarios_fisicos',
    CLIENTES: 'clientes',
    CATEGORIAS: 'categorias',
    LABORATORIOS: 'laboratorios',
    FORMAS: 'formas',
    PRESENTACIONES: 'presentaciones',
    CONCENTRACIONES: 'concentraciones',
    VIAS: 'vias',
    RANGOS_EDAD: 'rangos_edad',
    MARCAS: 'marcas',
    PRODUCTOS: 'productos',
    PRODUCTOS_VIAS: 'productos_vias',
    EQUIVALENTES: 'equivalentes',
    PRODUCTOS_RANGOS_EDAD: 'productos_rangos_edad',
    PRODUCTOS_UBICACIONES: 'productos_ubicaciones',
    PRINCIPIOS_ACTIVOS: 'principios_activos',
    PRODUCTOS_PRINCIPIOS: 'productos_principios',
    REGISTROS_SANITARIOS: 'registros_sanitarios',
    PRODUCTOS_CONTROLADOS: 'productos_controlados',
    PROMOCIONES: 'promociones',
    PROMOCIONES_PRODUCTOS: 'promociones_productos',
    CONVERSIONES_UNIDAD: 'conversiones_unidad',
    PROVEEDORES: 'proveedores',
    PROVEEDORES_CONTACTOS: 'proveedores_contactos',
    PROVEEDORES_RATING_HISTORICO: 'proveedores_rating_historico',
    PARAMETROS_GLOBALES: 'parametros_globales',
    TAREAS_PROGRAMADAS: 'tareas_programadas',
    CONTROL_FACTURAS: 'control_facturas',
    KARDEX: 'kardex',
    ORDENES_COMPRA: 'ordenes_compra',
    INSTITUCIONES: 'instituciones',
    ESPECIALIDADES: 'especialidades',
    MEDICOS: 'medicos',
    RECETAS: 'recetas',
    LOTES_PRODUCTOS: 'lotes_productos',
    KARDEX_PRODUCTOS: 'kardex_productos',
    INVENTARIOS_FISICOS_DETALLE: 'inventarios_fisicos_detalle',
    UBICACIONES_MOVIMIENTOS: 'ubicaciones_movimientos',
    UBICACIONES_HISTORIAL: 'ubicaciones_historial',
    TIPOS_PLANES_PAGO: 'tipos_planes_pago',
    PLANES_PAGOS: 'planes_pagos',
    COMPROBANTES_PAGOS: 'comprobantes_pagos',
    PAGOS: 'pagos',
    CAJAS: 'cajas',
    MOVIMIENTOS: 'movimientos',
    ARQUEOS_DETALLE: 'arqueos_detalle',
    ALERTAS_NOTIFICACIONES: 'alertas_notificaciones',
    MODELOS: 'modelos',
    ENTRENAMIENTOS: 'entrenamientos',
    METRICAS_RENDIMIENTO: 'metricas_rendimiento',
    PATRONES_CONSUMO: 'patrones_consumo',
    VARIABLES_EXOGENAS: 'variables_exogenas',
    UMBRALES_CONFIGURACION: 'umbrales_configuracion',
    LOGS_EJECUCION: 'logs_ejecucion',
    ANALITICA_PRODUCTOS: 'analitica_productos',
    PEDIDOS_ONLINE: 'pedidos_online',
    DETALLES_PEDIDOS_ONLINE: 'detalles_pedidos_online',
    CARRITOS_COMPRA: 'carritos_compra',
    DETALLES_CARRITOS: 'detalles_carritos',
    LISTAS_PRECIOS: 'listas_precios',
    PRECIOS_PRODUCTOS: 'precios_productos',
    COSTOS_PROMEDIO: 'costos_promedio',
    POLITICAS_PRECIOS: 'politicas_precios',
    ASISTENCIAS: 'asistencias',
    PLANILLAS: 'planillas',
    PLANILLAS_DETALLE: 'planillas_detalle',
    CONTRATOS: 'contratos',
    HISTORICOS: 'historicos',
} as const;

export type NombreTabla = typeof TABLAS[keyof typeof TABLAS];

export const TABLAS_ARRAY: NombreTabla[] = Object.values(TABLAS);

export function obtenerTodasLasTablas(): NombreTabla[] {
    return [...TABLAS_ARRAY];
}

export function esTablaValida(nombre: string): nombre is NombreTabla {
    return TABLAS_ARRAY.includes(nombre as NombreTabla);
}
